create sequence product_seq start with 1 increment by 50;
create sequence revinfo_seq start with 1 increment by 50;
create table category (name varchar(255) not null, primary key (name));
create table category_aud (rev integer not null, revtype smallint, name varchar(255) not null, primary key (rev, name));
create table product (price integer not null, id bigint not null, category_name varchar(255), name varchar(255), primary key (id));
create table product_aud (price integer, rev integer not null, revtype smallint, id bigint not null, category_name varchar(255), name varchar(255), primary key (rev, id));
create table revinfo (rev integer not null, revtstmp bigint, primary key (rev));
alter table if exists category_aud add constraint FKc9m640crhsib2ws80um6xuk1w foreign key (rev) references revinfo;
alter table if exists product add constraint FKmxhoec7wquhjv31p300vqahdo foreign key (category_name) references category;
alter table if exists product_aud add constraint FK9vwllld6jlw5xys1ay911oh1x foreign key (rev) references revinfo;
