/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hu.cubix.catalogservice.patrik.api;

import hu.cubix.catalogservice.patrik.model.CategoryDto;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-02-26T21:26:59.725292900+01:00[Europe/Budapest]")
@Validated
@Tag(name = "CategoryController", description = "the CategoryController API")
public interface CategoryControllerApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /api/categories : Create new category
     * Endpoint for add new category.
     *
     * @param categoryDto  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "addCategory",
        summary = "Create new category",
        description = "Endpoint for add new category.",
        tags = { "category-controller" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CategoryDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/categories",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<CategoryDto> addCategory(
        @Parameter(name = "CategoryDto", description = "", required = true) @Valid @RequestBody CategoryDto categoryDto
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"name\" : \"name\", \"products\" : [ { \"price\" : 0, \"name\" : \"name\", \"id\" : 0 }, { \"price\" : 0, \"name\" : \"name\", \"id\" : 0 } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /api/categories : Get all categories
     * Retrieve categories.
     *
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "findAllCategories",
        summary = "Get all categories",
        description = "Retrieve categories.",
        tags = { "category-controller" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = CategoryDto.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/categories",
        produces = { "application/json" }
    )
    default ResponseEntity<List<CategoryDto>> findAllCategories(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"name\" : \"name\", \"products\" : [ { \"price\" : 0, \"name\" : \"name\", \"id\" : 0 }, { \"price\" : 0, \"name\" : \"name\", \"id\" : 0 } ] }, { \"name\" : \"name\", \"products\" : [ { \"price\" : 0, \"name\" : \"name\", \"id\" : 0 }, { \"price\" : 0, \"name\" : \"name\", \"id\" : 0 } ] } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
